mindmap
  root((Microservices System))
    Execution
      Internal communication
      Liveness
      Readiness
      Health
    Networking
    Storage
      Persistent
        Internal
        Node
        Cluster
      Configuration
        Share
        Updates
        Secrets
    Version Management
      Updates
        Canary
        Blue-green
      Rollback
    Resilience / Scalability
    Resources Management
      Limits
      Balancing
    Communication
      Internal
      External
      Balancing
    Security
      User account
      Authentication
      Authorization
      Network policies