apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
  labels:
    app: my-nginx #importante para relacionar objetos
  annotations:
    kubernetes.io/change-cause: "Initial Deployment"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-nginx #objetos a los que afecta
  template:
    metadata:
      labels:
        app: my-nginx #etiqueta custom para asociar este objeto
    spec: # definición de los Pods
      containers:
      - name: my-nginx
        image: nginx:alpine # imagen de nginx
        ports:
        - containerPort: 80 #solo informativo
        resources: # acá pueden ir cosas como límites de CPU y memoria